

# This configuration was tested to work on a local kind cluster.

controller:
  ingressClassResource:
    default: true
    name: ${ingressClassName}
  replicaCount: ${replicas}
  ingressClass: non-existing
  admissionWebhooks:
    enabled: false
  hostNetwork: true
  service:
    type: NodePort
