# DO NOT EDIT THIS FILE
# doing so will disqualify your submission

# we configured the Kubenetes and Helm providers for you so they
# work with your local kind cluster

provider "kubernetes" {
  # Docs: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs
  config_path    = "~/.kube/config"
  config_context = local.cluster_context
}

provider "helm" {
  # Docs: https://registry.terraform.io/providers/hashicorp/helm/latest/docs
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = local.cluster_context
  }
}
