# DO NOT EDIT THIS FILE
# doing so will disqualify your submission

# we configured the AWS provider for you so it works with a locally running
# Localstack instead of AWS

provider "aws" {
  access_key = "mock_access_key"
  secret_key = "mock_secret_key"
  region     = "us-east-1"

  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    s3 = "http://127.0.0.1:4566" # Localstack S3 service
  }
}
